module Nba
  TEAMS = {
    "New York Knicks"        => { :abbr => "NYK", :div => "atlantic",  :conference => "eastern" },
    "Boston Celtics"         => { :abbr => "BOS", :div => "atlantic",  :conference => "eastern" },
    "Dallas Mavericks"       => { :abbr => "DAL", :div => "southwest", :conference => "western" },
    "Miami Heat"             => { :abbr => "MIA", :div => "southeast", :conference => "eastern" },
    "Los Angeles Lakers"     => { :abbr => "LAL", :div => "pacific",   :conference => "western" },
    "Chicago Bulls"          => { :abbr => "CHI", :div => "central",   :conference => "eastern" },
    "Oklahoma City Thunder"  => { :abbr => "OKC", :div => "northwest", :conference => "western" },
    "Orlando Magic"          => { :abbr => "ORL", :div => "southeast", :conference => "eastern" },
    "Golden State Warriors"  => { :abbr => "GSW", :div => "pacific",   :conference => "western" },
    "Los Angeles Clippers"   => { :abbr => "LAC", :div => "pacific",   :conference => "western" },
    "Cleveland Cavaliers"    => { :abbr => "CLE", :div => "central",   :conference => "eastern" },
    "Toronto Raptors"        => { :abbr => "TOR", :div => "atlantic",  :conference => "eastern" },
    "Indiana Pacers"         => { :abbr => "IND", :div => "central",   :conference => "eastern" },
    "Detroit Pistons"        => { :abbr => "DET", :div => "central",   :conference => "eastern" },
    "Houston Rockets"        => { :abbr => "HOU", :div => "southwest", :conference => "western" },
    "Washington Wizards"     => { :abbr => "WAS", :div => "southeast", :conference => "eastern" },
    "New Jersey Nets"        => { :abbr => "NJN", :div => "atlantic",  :conference => "eastern" },
    "Brooklyn Nets"          => { :abbr => "BKN", :div => "atlantic",  :conference => "eastern" },
    "Charlotte Bobcats"      => { :abbr => "CHA", :div => "southeast", :conference => "eastern" },
    "Milwaukee Bucks"        => { :abbr => "MIL", :div => "central",   :conference => "eastern" },
    "Minnesota Timberwolves" => { :abbr => "MIN", :div => "northwest", :conference => "western" },
    "Denver Nuggets"         => { :abbr => "DEN", :div => "northwest", :conference => "western" },
    "San Antonio Spurs"      => { :abbr => "SAN", :div => "southwest", :conference => "western" },
    "Memphis Grizzlies"      => { :abbr => "MEM", :div => "southwest", :conference => "western" },
    "Phoenix Suns"           => { :abbr => "PHX", :div => "pacific",   :conference => "western" },
    "New Orleans Hornets"    => { :abbr => "NOH", :div => "southwest", :conference => "western" },
    "Portland Trail Blazers" => { :abbr => "POR", :div => "northwest", :conference => "western" },
    "Philadelphia 76ers"     => { :abbr => "PHI", :div => "atlantic",  :conference => "eastern" },
    "Sacramento Kings"       => { :abbr => "SAC", :div => "pacific",   :conference => "western" },
    "Atlanta Hawks"          => { :abbr => "ATL", :div => "southeast", :conference => "eastern" },
    "Utah Jazz"              => { :abbr => "UTA", :div => "northwest", :conference => "western" }
  }
end
