development:
  sessions:
    default:
      uri: <%= "mongodb://localhost:27017/development" %>
test:
  sessions:
    default:
      uri: mongodb://localhost:27017/test
    with_data:
      uri: mongodb://localhost:27017/test_with_data
production:
  sessions:
    default:
      uri: <%= ((defined? params) && params['mongohq_url']) ? params['mongohq_url'] : ENV['MONGOHQ_URL'] %>
