development:
  sessions:
    default:
      uri: <%= "mongodb://localhost:27017/main" %>
test:
  sessions:
    default:
      uri: mongodb://localhost:27017/test
production:
  sessions:
    default:
      uri: <%= ((defined? params) && params['mongohq_url']) ? params['mongohq_url'] : ENV['MONGOHQ_URL'] %>
